/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleRouteImport } from './routes/style'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppPacientesRouteImport } from './routes/_authenticated.app.pacientes'
import { Route as AuthenticatedAppFunilRouteImport } from './routes/_authenticated.app.funil'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated.app.agenda'
import { Route as AuthenticatedAppConversasIndexRouteImport } from './routes/_authenticated.app.conversas.index'
import { Route as AuthenticatedAppConfiguracoesIndexRouteImport } from './routes/_authenticated.app.configuracoes.index'
import { Route as ApiPublicHooksReguasCronRouteImport } from './routes/api/public/hooks/reguas-cron'
import { Route as AuthenticatedAppPacientesPacienteIdRouteImport } from './routes/_authenticated.app.pacientes.$pacienteId'
import { Route as AuthenticatedAppConversasConversaIdRouteImport } from './routes/_authenticated.app.conversas.$conversaId'
import { Route as AuthenticatedAppConfiguracoesZapiRouteImport } from './routes/_authenticated.app.configuracoes.zapi'
import { Route as AuthenticatedAppConfiguracoesVariaveisRouteImport } from './routes/_authenticated.app.configuracoes.variaveis'
import { Route as AuthenticatedAppConfiguracoesClinicaRouteImport } from './routes/_authenticated.app.configuracoes.clinica'
import { Route as AuthenticatedAppConfiguracoesAutomacoesRouteImport } from './routes/_authenticated.app.configuracoes.automacoes'
import { Route as AuthenticatedAppConfiguracoesAgendaRouteImport } from './routes/_authenticated.app.configuracoes.agenda'

const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPacientesRoute =
  AuthenticatedAppPacientesRouteImport.update({
    id: '/pacientes',
    path: '/pacientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFunilRoute = AuthenticatedAppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConversasIndexRoute =
  AuthenticatedAppConversasIndexRouteImport.update({
    id: '/conversas/',
    path: '/conversas/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesIndexRoute =
  AuthenticatedAppConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksReguasCronRoute =
  ApiPublicHooksReguasCronRouteImport.update({
    id: '/api/public/hooks/reguas-cron',
    path: '/api/public/hooks/reguas-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppPacientesPacienteIdRoute =
  AuthenticatedAppPacientesPacienteIdRouteImport.update({
    id: '/$pacienteId',
    path: '/$pacienteId',
    getParentRoute: () => AuthenticatedAppPacientesRoute,
  } as any)
const AuthenticatedAppConversasConversaIdRoute =
  AuthenticatedAppConversasConversaIdRouteImport.update({
    id: '/conversas/$conversaId',
    path: '/conversas/$conversaId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesZapiRoute =
  AuthenticatedAppConfiguracoesZapiRouteImport.update({
    id: '/configuracoes/zapi',
    path: '/configuracoes/zapi',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesVariaveisRoute =
  AuthenticatedAppConfiguracoesVariaveisRouteImport.update({
    id: '/configuracoes/variaveis',
    path: '/configuracoes/variaveis',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesClinicaRoute =
  AuthenticatedAppConfiguracoesClinicaRouteImport.update({
    id: '/configuracoes/clinica',
    path: '/configuracoes/clinica',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesAutomacoesRoute =
  AuthenticatedAppConfiguracoesAutomacoesRouteImport.update({
    id: '/configuracoes/automacoes',
    path: '/configuracoes/automacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesAgendaRoute =
  AuthenticatedAppConfiguracoesAgendaRouteImport.update({
    id: '/configuracoes/agenda',
    path: '/configuracoes/agenda',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/style': typeof StyleRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/funil': typeof AuthenticatedAppFunilRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/configuracoes/agenda': typeof AuthenticatedAppConfiguracoesAgendaRoute
  '/app/configuracoes/automacoes': typeof AuthenticatedAppConfiguracoesAutomacoesRoute
  '/app/configuracoes/clinica': typeof AuthenticatedAppConfiguracoesClinicaRoute
  '/app/configuracoes/variaveis': typeof AuthenticatedAppConfiguracoesVariaveisRoute
  '/app/configuracoes/zapi': typeof AuthenticatedAppConfiguracoesZapiRoute
  '/app/conversas/$conversaId': typeof AuthenticatedAppConversasConversaIdRoute
  '/app/pacientes/$pacienteId': typeof AuthenticatedAppPacientesPacienteIdRoute
  '/api/public/hooks/reguas-cron': typeof ApiPublicHooksReguasCronRoute
  '/app/configuracoes/': typeof AuthenticatedAppConfiguracoesIndexRoute
  '/app/conversas/': typeof AuthenticatedAppConversasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/style': typeof StyleRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/funil': typeof AuthenticatedAppFunilRoute
  '/app/pacientes': typeof AuthenticatedAppPacientesRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/configuracoes/agenda': typeof AuthenticatedAppConfiguracoesAgendaRoute
  '/app/configuracoes/automacoes': typeof AuthenticatedAppConfiguracoesAutomacoesRoute
  '/app/configuracoes/clinica': typeof AuthenticatedAppConfiguracoesClinicaRoute
  '/app/configuracoes/variaveis': typeof AuthenticatedAppConfiguracoesVariaveisRoute
  '/app/configuracoes/zapi': typeof AuthenticatedAppConfiguracoesZapiRoute
  '/app/conversas/$conversaId': typeof AuthenticatedAppConversasConversaIdRoute
  '/app/pacientes/$pacienteId': typeof AuthenticatedAppPacientesPacienteIdRoute
  '/api/public/hooks/reguas-cron': typeof ApiPublicHooksReguasCronRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesIndexRoute
  '/app/conversas': typeof AuthenticatedAppConversasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/style': typeof StyleRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/funil': typeof AuthenticatedAppFunilRoute
  '/_authenticated/app/pacientes': typeof AuthenticatedAppPacientesRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/configuracoes/agenda': typeof AuthenticatedAppConfiguracoesAgendaRoute
  '/_authenticated/app/configuracoes/automacoes': typeof AuthenticatedAppConfiguracoesAutomacoesRoute
  '/_authenticated/app/configuracoes/clinica': typeof AuthenticatedAppConfiguracoesClinicaRoute
  '/_authenticated/app/configuracoes/variaveis': typeof AuthenticatedAppConfiguracoesVariaveisRoute
  '/_authenticated/app/configuracoes/zapi': typeof AuthenticatedAppConfiguracoesZapiRoute
  '/_authenticated/app/conversas/$conversaId': typeof AuthenticatedAppConversasConversaIdRoute
  '/_authenticated/app/pacientes/$pacienteId': typeof AuthenticatedAppPacientesPacienteIdRoute
  '/api/public/hooks/reguas-cron': typeof ApiPublicHooksReguasCronRoute
  '/_authenticated/app/configuracoes/': typeof AuthenticatedAppConfiguracoesIndexRoute
  '/_authenticated/app/conversas/': typeof AuthenticatedAppConversasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/style'
    | '/app'
    | '/app/agenda'
    | '/app/funil'
    | '/app/pacientes'
    | '/app/'
    | '/app/configuracoes/agenda'
    | '/app/configuracoes/automacoes'
    | '/app/configuracoes/clinica'
    | '/app/configuracoes/variaveis'
    | '/app/configuracoes/zapi'
    | '/app/conversas/$conversaId'
    | '/app/pacientes/$pacienteId'
    | '/api/public/hooks/reguas-cron'
    | '/app/configuracoes/'
    | '/app/conversas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/style'
    | '/app/agenda'
    | '/app/funil'
    | '/app/pacientes'
    | '/app'
    | '/app/configuracoes/agenda'
    | '/app/configuracoes/automacoes'
    | '/app/configuracoes/clinica'
    | '/app/configuracoes/variaveis'
    | '/app/configuracoes/zapi'
    | '/app/conversas/$conversaId'
    | '/app/pacientes/$pacienteId'
    | '/api/public/hooks/reguas-cron'
    | '/app/configuracoes'
    | '/app/conversas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/style'
    | '/_authenticated/app'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/funil'
    | '/_authenticated/app/pacientes'
    | '/_authenticated/app/'
    | '/_authenticated/app/configuracoes/agenda'
    | '/_authenticated/app/configuracoes/automacoes'
    | '/_authenticated/app/configuracoes/clinica'
    | '/_authenticated/app/configuracoes/variaveis'
    | '/_authenticated/app/configuracoes/zapi'
    | '/_authenticated/app/conversas/$conversaId'
    | '/_authenticated/app/pacientes/$pacienteId'
    | '/api/public/hooks/reguas-cron'
    | '/_authenticated/app/configuracoes/'
    | '/_authenticated/app/conversas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StyleRoute: typeof StyleRoute
  ApiPublicHooksReguasCronRoute: typeof ApiPublicHooksReguasCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pacientes': {
      id: '/_authenticated/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AuthenticatedAppPacientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/funil': {
      id: '/_authenticated/app/funil'
      path: '/funil'
      fullPath: '/app/funil'
      preLoaderRoute: typeof AuthenticatedAppFunilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conversas/': {
      id: '/_authenticated/app/conversas/'
      path: '/conversas'
      fullPath: '/app/conversas/'
      preLoaderRoute: typeof AuthenticatedAppConversasIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/': {
      id: '/_authenticated/app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/reguas-cron': {
      id: '/api/public/hooks/reguas-cron'
      path: '/api/public/hooks/reguas-cron'
      fullPath: '/api/public/hooks/reguas-cron'
      preLoaderRoute: typeof ApiPublicHooksReguasCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/pacientes/$pacienteId': {
      id: '/_authenticated/app/pacientes/$pacienteId'
      path: '/$pacienteId'
      fullPath: '/app/pacientes/$pacienteId'
      preLoaderRoute: typeof AuthenticatedAppPacientesPacienteIdRouteImport
      parentRoute: typeof AuthenticatedAppPacientesRoute
    }
    '/_authenticated/app/conversas/$conversaId': {
      id: '/_authenticated/app/conversas/$conversaId'
      path: '/conversas/$conversaId'
      fullPath: '/app/conversas/$conversaId'
      preLoaderRoute: typeof AuthenticatedAppConversasConversaIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/zapi': {
      id: '/_authenticated/app/configuracoes/zapi'
      path: '/configuracoes/zapi'
      fullPath: '/app/configuracoes/zapi'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesZapiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/variaveis': {
      id: '/_authenticated/app/configuracoes/variaveis'
      path: '/configuracoes/variaveis'
      fullPath: '/app/configuracoes/variaveis'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesVariaveisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/clinica': {
      id: '/_authenticated/app/configuracoes/clinica'
      path: '/configuracoes/clinica'
      fullPath: '/app/configuracoes/clinica'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesClinicaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/automacoes': {
      id: '/_authenticated/app/configuracoes/automacoes'
      path: '/configuracoes/automacoes'
      fullPath: '/app/configuracoes/automacoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesAutomacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes/agenda': {
      id: '/_authenticated/app/configuracoes/agenda'
      path: '/configuracoes/agenda'
      fullPath: '/app/configuracoes/agenda'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppPacientesRouteChildren {
  AuthenticatedAppPacientesPacienteIdRoute: typeof AuthenticatedAppPacientesPacienteIdRoute
}

const AuthenticatedAppPacientesRouteChildren: AuthenticatedAppPacientesRouteChildren =
  {
    AuthenticatedAppPacientesPacienteIdRoute:
      AuthenticatedAppPacientesPacienteIdRoute,
  }

const AuthenticatedAppPacientesRouteWithChildren =
  AuthenticatedAppPacientesRoute._addFileChildren(
    AuthenticatedAppPacientesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppFunilRoute: typeof AuthenticatedAppFunilRoute
  AuthenticatedAppPacientesRoute: typeof AuthenticatedAppPacientesRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppConfiguracoesAgendaRoute: typeof AuthenticatedAppConfiguracoesAgendaRoute
  AuthenticatedAppConfiguracoesAutomacoesRoute: typeof AuthenticatedAppConfiguracoesAutomacoesRoute
  AuthenticatedAppConfiguracoesClinicaRoute: typeof AuthenticatedAppConfiguracoesClinicaRoute
  AuthenticatedAppConfiguracoesVariaveisRoute: typeof AuthenticatedAppConfiguracoesVariaveisRoute
  AuthenticatedAppConfiguracoesZapiRoute: typeof AuthenticatedAppConfiguracoesZapiRoute
  AuthenticatedAppConversasConversaIdRoute: typeof AuthenticatedAppConversasConversaIdRoute
  AuthenticatedAppConfiguracoesIndexRoute: typeof AuthenticatedAppConfiguracoesIndexRoute
  AuthenticatedAppConversasIndexRoute: typeof AuthenticatedAppConversasIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppFunilRoute: AuthenticatedAppFunilRoute,
  AuthenticatedAppPacientesRoute: AuthenticatedAppPacientesRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppConfiguracoesAgendaRoute:
    AuthenticatedAppConfiguracoesAgendaRoute,
  AuthenticatedAppConfiguracoesAutomacoesRoute:
    AuthenticatedAppConfiguracoesAutomacoesRoute,
  AuthenticatedAppConfiguracoesClinicaRoute:
    AuthenticatedAppConfiguracoesClinicaRoute,
  AuthenticatedAppConfiguracoesVariaveisRoute:
    AuthenticatedAppConfiguracoesVariaveisRoute,
  AuthenticatedAppConfiguracoesZapiRoute:
    AuthenticatedAppConfiguracoesZapiRoute,
  AuthenticatedAppConversasConversaIdRoute:
    AuthenticatedAppConversasConversaIdRoute,
  AuthenticatedAppConfiguracoesIndexRoute:
    AuthenticatedAppConfiguracoesIndexRoute,
  AuthenticatedAppConversasIndexRoute: AuthenticatedAppConversasIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StyleRoute: StyleRoute,
  ApiPublicHooksReguasCronRoute: ApiPublicHooksReguasCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
